Intg 423
invitation-homes/mulesoft-build-action pull request #1
Opened 2021-04-14 11:37 UTC by faisalkhanani-ih

2021-04-15 13:10 UTC, edwagner requested changes
Overall this look really nice. Just a few suggestions around how to pass inputs (both parameters & secrets) and simplifying the creation of the maven settings file.

2021-04-15 13:10 UTC, edwagner commented on src/maven.js
> +function generateMavenSettings(mavenSettings) {
Can't we simplify this? i.e. just do string interpolation starting with a simple hard-coded settings.xml that includes our repositories and inject in the nexus credentials from the environment variables? I don't think we need all this ability to fully customize every section.

2021-04-16 11:21 UTC, faisalkhanani-ih commented on action.yml
> +  GITHUB_TOKEN:
https://github.com/invitation-homes/mulesoft-build-action/pull/2
Done in above PR

2021-04-16 11:21 UTC, faisalkhanani-ih commented on action.yml
> +  buildArgs:
https://github.com/invitation-homes/mulesoft-build-action/pull/2
Done in above PR.

2021-04-16 11:23 UTC, faisalkhanani-ih commented on action.yml
> +  testArgs:
We will have to keep this input as is. In above example, we only have one value to pass but in our case it will be more than one and we will need them as list/array, so we can pass them as -Denv=xxx, -Dsecret.key=xxx, -Dsystem.client.id=xxx etc.

2021-04-16 11:24 UTC, faisalkhanani-ih commented on src/maven.js
> +function generateMavenSettings(mavenSettings) {
I have made the change as per your advice in https://github.com/invitation-homes/mulesoft-build-action/pull/2 PR but the only caveat is action repo is public and in template we are revealing our private maven repo url.

2021-04-16 21:23 UTC, edwagner requested changes
Thanks Faisal. I would recommend making the changes as an additional commit on this branch rather than creating another PR. That way all of the conversation about a given feature is captured in one place (i.e. on this PR). I would only open a new PR if the first one had gotten merged.

2021-04-16 21:23 UTC, edwagner commented on src/maven.js
> +function generateMavenSettings(mavenSettings) {
What is the private maven repo URL that you are talking about? Neither of the repos (releases nor nexus-ee) look sensitive to me. Also for the environment variables, is there a reason to pass them in as parameters? Can you just use `process.env.mulesoft_nexus_user` wherever you need it?

2021-04-16 21:23 UTC, edwagner commented on action.yml
> +  testArgs:
I guess I don't understand why we need to pass any of those in. Why can't those just be hardcoded in the action itself? Will they be different for different repositories?
Do the values for `secret.key` and `system.client.id` need to be valid, or do we just need some placeholder text?

2021-04-18 12:14 UTC, faisalkhanani-ih commented on action.yml
> +  testArgs:
`Will they be different for different repositories?`
Correct. They are different for different repositories and this way other teams can also include their runtime arguments.

`Do the values for secret.key and system.client.id need to be valid, or do we just need some placeholder text?`
For secret.key we are using GitHub secret and we need it's valid value. for others their keys are rather more important than values.

To avoid confusion, I am also moving them to environment variables.

2021-04-18 12:18 UTC, faisalkhanani-ih commented on src/maven.js
> +function generateMavenSettings(mavenSettings) {
You are correct. I have done it the exact same in above PR.

2021-04-18 12:19 UTC, faisalkhanani-ih commented
> Thanks Faisal. I would recommend making the changes as an additional commit on this branch rather than creating another PR. That way all of the conversation about a given feature is captured in one place (i.e. on this PR). I would only open a new PR if the first one had gotten merged.

Sure. I will move all the changes here.

2021-04-18 19:39 UTC, edwagner commented on action.yml
> +  testArgs:
I think that this is more or less what you are proposing, but I would suggest hardcoding `-Denv=local` and passing the `secret.key` as an environment variable fed from the `MULESOFT_SECRET_KEY_LOCAL` secret (which I just created).
Do we really need to pass `system.client.id`? Shouldn't that be fetched from the properties file?

2021-04-18 19:57 UTC, edwagner commented on src/maven.js
> +function generateMavenSettings(mavenSettings) {
You're right, I take back my suggestion about using `process.env.mulesoft_nexus_user` inside of `build()`. I'm no fan of global variables and there is value to using parameters to clarify what inputs a function needs to work properly. I like that you're only accessing the environment variables in the `main()` function. That seems more modular.

2021-04-20 07:25 UTC, faisalkhanani-ih commented on action.yml
> +  testArgs:
let's discuss this in today's call.

2021-04-23 13:50 UTC, faisalkhanani commented on action.yml
> +  testArgs:
As discussed I am passing the secret.key as environment variable and since environment will always be local, so putting the hardcoded values for it.

2021-04-23 17:16 UTC, edwagner reviewed
I think all that remains is adding some content to the README to explain what this does and how to use it (e.g. an example workflow snippet that passes parameters & env variables), as well as a LICENSE file like https://github.com/invitation-homes/check-pom-uprev-action/blob/main/LICENSE and squashing the commits

2021-04-26 13:32 UTC, edwagner requested changes
Sorry to belabor this, but I think it's important to get the interface right, since this will likely be the example of other actions.

2021-04-26 13:32 UTC, edwagner commented on README.md
> +Mulesoft build action compiles/build Mulesoft maven project, create a release on GitHub, upload and associate build artifact with a produced release.
```suggestion
A GitHub Action that uses maven to compile a jar from a Mulesoft project, creates a release on GitHub, and uploads the jar to that release.
```

2021-04-26 13:32 UTC, edwagner commented on README.md
> +          github_token:  "GITHUB_TOKEN"
After looking at some of the official actions, it seems like the convention is for environment variable names to be upper case, e.g.
```
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I'll grant you that there is plenty of variety out there, but upper case seems to be the most prevalent. That's how we've named our secrets too, so it's probably best to be consistent with upper case. We should do that here as well as in the JavaScript code (which is mostly the case already).

2021-04-26 13:32 UTC, edwagner commented on README.md
> +          mulesoft_nexus_user: "MULESOFT Enterprise Repo. User"
I would go ahead and include the actual `${{ secrets.MULESOFT_NEXUS_USER }}` or whatever on the right side. Make it easy for our other developers to just cut & paste the code into their workflow.

2021-04-26 13:32 UTC, edwagner commented on src/index.js
> +  const secret_key = process.env.secret_key;
As I mentioned above, let's make these all upper case
```suggestion
  const SECRET_KEY = process.env.SECRET_KEY;
```

2021-04-26 13:32 UTC, edwagner commented on action.yml
> +    description: 'release number to be build'
Why does it need the release number? Can't it figure that out from the pom?

2021-04-26 13:32 UTC, edwagner commented on template/settings.xml
> +<settings
Maybe rename this file to be `template/maven-settings.xml`, just to be clearer

2021-04-27 11:48 UTC, edwagner approved these changes

2021-04-28 07:03 UTC, merged